### ISSUE TITLE
Broken hamburger menu

### ISSUE THREAD

**Issue by HatGuy68** [HatGuy68/SaveTabAsSession#5]
## Current Behavior
No action

## Expected Behavior
A menu should slide in with options to be decided in the future. It should have a footer with external links.

**Comment by ShaziahGafur** [comment]
Hi, I can work on this feature

**Comment by HatGuy68** [comment]
Go for it.

**Comment by ShaziahGafur** [comment]
Implemented. Please see PR: https://github.com/HatGuy68/SaveTabAsSession/pull/7
